id: P22BCE688
initial_creation_type: input
source_metadata:
  Title: Bodhipathpradipa of Atisha
  Editor: Shastri, Losang Norbu, ed.
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: India
  Year: '1984'
  Bodhipathapradīpaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:42:39.380519'
last_modified_at: '2022-03-08T16:42:39.380529'
